"""Add composite unique constraints on membership and rules tables

Revision ID: 2cf7a5f044f4
Revises: 7c65288af4a6
Create Date: 2026-07-03 18:38:43.839429

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2cf7a5f044f4'
down_revision: Union[str, Sequence[str], None] = '7c65288af4a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_insurance_rule_per_week', 'insurance_rules', ['league_id', 'season_id', 'week_number'])
    op.create_unique_constraint('uq_league_member_per_season', 'league_members', ['league_id', 'user_id', 'season_id'])
    op.create_unique_constraint('uq_league_rule_per_season', 'league_rules', ['league_id', 'season_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_league_rule_per_season', 'league_rules', type_='unique')
    op.drop_constraint('uq_league_member_per_season', 'league_members', type_='unique')
    op.drop_constraint('uq_insurance_rule_per_week', 'insurance_rules', type_='unique')
    # ### end Alembic commands ###
