"""Add league_members, league_rules, insurance_rules, and weeks tables

Revision ID: 7c65288af4a6
Revises: ace241e8f5e7
Create Date: 2026-07-03 18:10:52.645786

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c65288af4a6'
down_revision: Union[str, Sequence[str], None] = 'ace241e8f5e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('insurance_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('insurance_allowance', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_insurance_rules_id'), 'insurance_rules', ['id'], unique=False)
    op.create_table('league_members',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('member_role', sa.Enum('commissioner', 'player', name='member_role_enum'), nullable=False),
    sa.Column('buy_in_amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('initial_seed_money', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_members_id'), 'league_members', ['id'], unique=False)
    op.create_table('league_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('global_minimum_wager', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('favorite_odds_threshold', sa.Integer(), nullable=False),
    sa.Column('favorite_odds_ceiling', sa.Integer(), nullable=False),
    sa.Column('predictions_lock_date', sa.Date(), nullable=False),
    sa.Column('usd_to_seed_money_conversion', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('minimum_usd_buy_in', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('maximum_insurance_refund', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('postseason_wagering_enabled', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['league_id'], ['leagues.id'], ),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_league_rules_id'), 'league_rules', ['id'], unique=False)
    op.create_table('weeks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('season_id', sa.Integer(), nullable=False),
    sa.Column('week_number', sa.Integer(), nullable=False),
    sa.Column('week_status', sa.Enum('active', 'concluded', name='week_status_enum'), nullable=False),
    sa.Column('is_postseason', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['season_id'], ['seasons.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weeks_id'), 'weeks', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_weeks_id'), table_name='weeks')
    op.drop_table('weeks')
    op.drop_index(op.f('ix_league_rules_id'), table_name='league_rules')
    op.drop_table('league_rules')
    op.drop_index(op.f('ix_league_members_id'), table_name='league_members')
    op.drop_table('league_members')
    op.drop_index(op.f('ix_insurance_rules_id'), table_name='insurance_rules')
    op.drop_table('insurance_rules')
    # ### end Alembic commands ###
