"""Add nfl_teams, nfl_players, and leagues tables

Revision ID: ace241e8f5e7
Revises: 6cdb34f69f1b
Create Date: 2026-07-03 17:49:59.920034

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ace241e8f5e7'
down_revision: Union[str, Sequence[str], None] = '6cdb34f69f1b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leagues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('league_name', sa.String(), nullable=False),
    sa.Column('join_code', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_leagues_id'), 'leagues', ['id'], unique=False)
    op.create_index(op.f('ix_leagues_join_code'), 'leagues', ['join_code'], unique=True)
    op.create_table('nfl_teams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_name', sa.String(), nullable=False),
    sa.Column('conference', sa.String(), nullable=False),
    sa.Column('division', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('team_name')
    )
    op.create_index(op.f('ix_nfl_teams_id'), 'nfl_teams', ['id'], unique=False)
    op.create_table('nfl_players',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('first_name', sa.String(), nullable=False),
    sa.Column('last_name', sa.String(), nullable=False),
    sa.Column('team_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['team_id'], ['nfl_teams.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_nfl_players_id'), 'nfl_players', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_nfl_players_id'), table_name='nfl_players')
    op.drop_table('nfl_players')
    op.drop_index(op.f('ix_nfl_teams_id'), table_name='nfl_teams')
    op.drop_table('nfl_teams')
    op.drop_index(op.f('ix_leagues_join_code'), table_name='leagues')
    op.drop_index(op.f('ix_leagues_id'), table_name='leagues')
    op.drop_table('leagues')
    # ### end Alembic commands ###
